export const APP_ROUTES = {
  home: '/',
  login: '/login',
  setPassword: '/set-password',
  profile: '/profile',
  user: {
    dashboard: '/dashboard',
    school: '/school',
  },
  developer: {
    root: '/developer',
    dashboard: '/developer/dashboard',
    schools: '/developer/schools',
    userAccounts: '/developer/users',
    schoolFeatures: '/developer/modules',
    messageConfig: '/developer/messages',
    accessControl: '/developer/access-control',
    branding: '/developer/branding',
    auditLogs: '/developer/audit-logs',
    webAppSettings: '/developer/settings',
  },
  school: {
    admin: {
      dashboard: '/dashboard',
      school: '/school',
      staff: '/staff',
      students: '/students',
      fees: '/fees',
      classes: '/classes',
      syllabus: '/syllabus',
      exams: '/exams',
      results: '/results',
    },
    teacher: {
      dashboard: '/dashboard',
      school: '/school',
      staff: '/staff',
      students: '/students',
      classes: '/classes',
      syllabus: '/syllabus',
      exams: '/exams',
      results: '/results',
    },
    staff: {
      dashboard: '/dashboard',
      school: '/school',
      staff: '/staff',
      students: '/students',
      fees: '/fees',
      classes: '/classes',
      results: '/results',
    },
    student: {
      dashboard: '/dashboard',
      classes: '/classes',
      syllabus: '/syllabus',
      attendance: '/attendance',
      fees: '/fees',
      results: '/results',
      profile: '/profile',
    },
  },
} as const;
